### ISSUE TITLE
Dark mode CSS

### ISSUE THREAD

**Issue by nfagerlund** [nfagerlund/eardogger-rs#2]
a lil treat for the new version. 

From dinking around earlier in the web inspector: 

```css
/* Eardogger dark mode css overrides */

:root {
  --color-background: #092A37;
  --color-text: #e4c485;
  --color-link: #62a4e6;
  --color-link-visited: #9d7bdd;
  --color-link-hover: #807ef7;
  --color-border: #888;
  --color-button-border: #888;
  --color-divider: grey;
  --color-danger: #7e1b16;
  --color-button: #710d45;
  --color-shadow: #825c49;
}
```

- To start with, auto-mode via the prefers-dark-mode css query.
- Later, add a cookie via JS to save light/dark/auto pref. (This should be per-device, so not in DB. Could conceivably go in session, but imo it should outlive the login cookie, so no.)
